using Godot;
using Godot.Collections;
using System.Text;

[Tool]
[GlobalClass]
public partial class InputRegistry : Resource {
  /*
   *
   * Registry Sync and Validation
   *
   */
  [ExportToolButton("Save and Validate", Icon = "Info")]
  private Callable SaveAndValidateButton => Callable.From(SaveAndValidate);

  private void SaveAndValidate() {
    var sb = new StringBuilder();
    sb.AppendLine("--- InputRegistry is running SaveAndValidate ---");
    sb.AppendLine("\nInput Actions:");
    if (Actions == null || Actions.Count == 0) {
      sb.AppendLine("\t⚠ No actions defined — generating empty InputActions class.");
    }

    sb.AppendLine(WriteActionsAndGetStatus());

    sb.AppendLine("\nInput Modes:");
    if (Modes == null || Modes.Count == 0) {
      sb.AppendLine("\t⚠ No input modes defined.");
    } else {
      sb.Append(GetModesStatus());
    }

    sb.AppendLine("\nInput Profile:");
    if (DefaultProfile == null) {
      sb.AppendLine("\t⚠ No default input profile assigned.");
    } else {
      sb.Append(GetProfileStatus());
    }

    GD.Print(sb.ToString());
  }

  [ExportCategory("Game Input Actions")]
  /*
   * Actions
   */
  [Export]
  public string SavePath { get; private set; } = "/generated/InputActions.gen.cs";

  [Export] public Array<InputActionSchema> Actions { get; private set; } = new();

  private string ResolvedPath => SavePath.StartsWith("res://")
    ? SavePath
    : "res://" + SavePath.TrimStart('/');

  private int _lastGeneratedHash;

  [ExportCategory("Game Input Modes")]
  /*
   * Modes
   */
  [Export]
  public Array<InputMode> Modes { get; private set; } = new();


  [ExportCategory("Game Input Profile")]
  /*
   * default game Input Profile (bindings)
   */
  [Export]
  public InputProfile DefaultProfile { get; private set; }

  private string WriteActionsAndGetStatus() {
    var output = GenerateOutputString();
    var hash = GD.Hash(output);
    if (hash == _lastGeneratedHash) {
      return "\t✓ Registry Actions are synced to code.";
    }

    WriteToFile(output);
    _lastGeneratedHash = hash;
    ResourceSaver.Save(this);
    return "\t✓ Registry Actions were out of sync — regenerated them.";
  }

  private string GetModesStatus() {
    var sb = new StringBuilder();
    foreach (var mode in Modes) {
      if (!mode.IsValid(out var errorMsg))
        sb.AppendLine($"\t⚠ InputMode error: {errorMsg}");
      else
        sb.AppendLine($"\t✓ InputMode {mode.ModeName} valid");
    }

    return sb.ToString();
  }

  private string GetProfileStatus() =>
    !DefaultProfile.IsValid(out var errorMsg, "\t") ? errorMsg : "\t✓ Default InputProfile is valid";


  private int GetHash() => GD.Hash(GenerateOutputString());


  /*
   *
   * File generator for static InputActions class.
   *
   */
  /// <summary>
  /// Generates a file which declares our static InputActions class.
  /// Scans all the registry's Actions and generates an output string from them.
  /// </summary>
  private void WriteToFile(string generatedOutput) {
    var dir = ResolvedPath.GetBaseDir();
    if (!DirAccess.DirExistsAbsolute(dir)) {
      DirAccess.MakeDirRecursiveAbsolute(dir);
    }

    using var file = FileAccess.Open(ResolvedPath, FileAccess.ModeFlags.Write);
    if (file == null) {
      GD.PushError($"Failed to open {ResolvedPath} for writing: {FileAccess.GetOpenError()}");
      return;
    }

    file.StoreString(generatedOutput);

    _lastGeneratedHash = GetHash();
    ResourceSaver.Save(this);
    GD.Print($"✓ Generated {ResolvedPath} with {Actions.Count} actions.");
  }

  /*
   * Helper
   */
  private string GenerateOutputString() {
    var sb = new StringBuilder();
    sb.AppendLine("// AUTO-GENERATED by InputRegistry. Do not edit by hand. How to use:");
    sb.AppendLine("//    1. Create an InputRegistry godot Resource");
    sb.AppendLine("//    2. Configure all the game's actions on it");
    sb.AppendLine("//    3. Click Sync Actions as Code in the GUI");
    sb.AppendLine();
    sb.AppendLine("using Godot;");
    sb.AppendLine("using System.Collections.Generic;");
    sb.AppendLine();
    sb.AppendLine("public static partial class InputActions {");

    foreach (var schema in Actions) {
      sb.AppendLine(schema.AsCodeDeclarationString());
    }

    sb.AppendLine("    static InputActions() {");
    sb.AppendLine("        All = new Dictionary<StringName, InputAction> {");
    foreach (var schema in Actions) {
      sb.AppendLine(schema.AsDictionaryEntryString());
    }

    sb.AppendLine("        };");
    sb.AppendLine("    }");

    sb.AppendLine("}");

    return sb.ToString();
  }
}